### ISSUE TITLE
Use `node-notifier` instead of reimplementing work

### ISSUE THREAD

**Issue by Turbo87** [vsolovyov/webpack-error-notification#1]
It would be easier to use https://github.com/mikaelbr/node-notifier instead of reimplementing everything. This plugin should only connect webpack and node-notifier and it would gain Windows support as well.

**Comment by vsolovyov** [comment]
Thank you for pointing to that project, I could look at it and try to add Windows support. 

But I really don't want to use a project with 5-10 dependencies instead of my literally eight lines of `STRATEGIES`.
